language: php

services:
  - redis-server
  - rabbitmq

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - phpenv config-rm xdebug.ini
  - if [[ "$TRAVIS_PHP_VERSION" != "5.3" && "$TRAVIS_PHP_VERSION" != "5.3.3" ]]; then composer require --no-update guzzlehttp/guzzle:~4; fi

install: make install

script: php --version && make test

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false
